version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      - run:
          name: compile
          command: npm run lint

workflows:
  node-workflow:
    jobs:
      - build